name: CI (Release)
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Publish
      run: dotnet publish .\Bloxstrap\Bloxstrap.csproj -c Release -p:PublishProfile=Publish-x64 -p:CommitHash=${{ github.sha }} -p:CommitRef=${{ github.ref_type }}/${{ github.ref_name }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      with:
        name: Froststrap(Release) (${{ github.sha }})
        path: .\Bloxstrap\bin\Release\net10.0-windows\publish\win-x64\*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Froststrap(Release) (${{ github.sha }})
          path: release

      - name: Rename binaries
        run: mv release/Froststrap.exe Froststrap-${{ github.ref_name }}.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: Froststrap-${{ github.ref_name }}.exe
          name: Froststrap ${{ github.ref_name }}
          fail_on_unmatched_files: true

  release-test:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/release-test')
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Froststrap(Release) (${{ github.sha }})
          path: release

      - name: Rename binaries
        run: mv release/Froststrap.exe Froststrap-${{ github.ref_name }}.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: Froststrap-${{ github.ref_name }}.exe
          name: Froststrap${{ github.ref_name }}
          fail_on_unmatched_files: true
